### ISSUE TITLE
The URLs for the APIs have changed. The following should work.

### ISSUE THREAD

**Issue by JuliusBlueTek** [andker87/Proscenic-M7-PRO#13]
`curl -v -k -X POST -H "os: i" -H "Content-Type: application/json" -H "c: 338" -H "lan: en" -H "Host: mobile.proscenic.tw" -H "User-Agent: ProscenicHome/1.7.8 (iPhone; iOS 14.2.1; Scale/3.00)" -H "v: 1.7.8" -d "{\"state\":\"欧洲\",\"countryCode\":\"49\",\"appVer\":\"1.7.8\",\"type\":\"2\",\"os\":\"IOS\",\"password\":\"$(echo -n $PASSWORD | md5sum)\",\"registrationId\":\"13165ffa4eb156ac484\",\"language\":\"EN\",\"username\":\"$LOGINUSER\",\"pwd\":\"$PASSWORD\"}" "https://mobile.proscenic.tw/user/login"`

The SN number can be gotten from:
`curl "https://mobile.proscenic.tw/user/getEquips/$LOGINUSER" -d "username=$LOGINUSER"`

The rest_commands.yaml needs to be changed to ->
```
rest_command:
  proscenic_clean:
    url: "https://mobile.proscenic.tw/instructions/cmd21005/{{ serial }}?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'cleanMode=sweepOnly&mode=smartAreaClean'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_deep_cleaning:
    url: "https://mobile.proscenic.tw/instructions/cmd21005_2/{{ serial }}?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'mode=depthTotalClean'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_collect_dust:
    url: "https://mobile.proscenic.tw/instructions/cmd/{{ serial }}?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: '{"dInfo":{"ts": "1675216377168","userId":"{{ username }}"},"data":{"cmd":"startDustCenter","value":0},"infoType":21024};'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_pause:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21017?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'mode=pause'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_continue:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21017?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'pauseOrContinue=continue'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_charge:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21012?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'charge=start'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_powermode_standard:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21022?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'setMode=auto'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_powermode_powerful:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21022?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'setMode=strong'
    content_type: 'application/x-www-form-urlencoded'

  proscenic_powermode_quiet:
    url: "https://mobile.proscenic.tw/instructions/{{ serial }}/21022?username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    payload: 'setMode=quiet'
    content_type: 'application/x-www-form-urlencoded'
```
