### ISSUE TITLE
Amazing work. Could you update the repo with the functions you havent reported?

### ISSUE THREAD

**Issue by Felix313** [andker87/Proscenic-M7-PRO#8]
Hi @andker87,

thank you so much for your amazing work! 

I'd love to use the M7 from homeassistant to use the multi-zone cleaning function. In the readme you mention that you have already managed to extract this function and just need to upload them here:

"
Already obtained (just need to report them here)

    generic infos (name, model, serial number and others)
    firmware informations
    avaibility
    last message(s) (cleaning completed, tank emptying in progress and others)
    zone cleaning function (based on automatic partition)
    multi-zone cleaning function (based on user defined zones)
    Y shaped mopping function
    set Silent (on/off)
    set Equipment light (on/off)
    auto dust collection (enable/disable)
    set volume
"
It would be amazing if you could add this functionality! 

Cheers,

Felix

**Comment by sschw56** [comment]
That would be great!

**Comment by Blueforcer** [comment]
also waiting for zone cleaning function <3

**Comment by Jandorello** [comment]
I think this is a good start:

```
  proscenic_zone:
    url: "https://mobile.proscenic.com.de:443/instructions/cmd21005/{{ serial }}/?segmentId=7&username={{ username }}"
    method: POST
    headers:
      host: "mobile.proscenic.com.de:443"
      token: "{{ token }}"
    content_type: 'application/json;charset=UTF-8'   
```

without reverse engineering the app, you probably have to guess that **segmentId=7** for your zone, but the command should be ok, than add a script in scripts.yaml that calls this proscenic_zone rest command and you are good to go
